# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YhOccJWemEarUOehFtCuGz9gevRmyoUlOk+KS0axFQ6tsHmMNdekbpDWwAvo9M6Ev4xIJBzkngRKFRarwJivdw4ugzlyBpGFDkiqfA5CozOU45t4HRsH1LqzkO5p+FTCfWgDJjO6JZjqRwtMA2VNXg1lZzU/GqefOtuJl6Bwg6f91sdpUYet+4tidWxYZVw1mmm+HNTxNtGpHcT9HZA9agjuq4xSKc7NkQbhAVPrttQuCU1O1DB6N8WTGtF508z5kgZe7S1ADgXQOQnvzKQsit3HMyyrXgioI466vNhdz+DyfEWRSWF9FAWgfBSleT9hBpqkNVn+m92snNWn9Je1c7fTjyjUfwirLTl5/dKd82dJOxREJS8GI5uBPgK9GBnhs6o+1P6+tBzvRSnbuCHkBQ/fVKvg6THAh2wydvk7bi2J5cQM+p5l/nJ2AV6kSscWZpnMgjrit0yL82oz0PfHr3p7GcTe9MS9ttKeZEpQLBRIqfDn+wGAxM1+E/dvGJ13labHPVroAIL1rXSmq1BtqZ5NqVzX8l3YM+OLVELIKixPiE6vN5q3EufHiwVnEbz3UWUJofPUvq5TNeSE+XIiaPbX39f2DMYyRgwjmAc5bwdFbKTaNHyI/Wtr1oPkmDsvoQd5am5NfwByP7c1Uujbcxzme1mLf/D3nLJcQOn//X4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
